### ISSUE TITLE
Specifics on hardware interface to Lutron system

### ISSUE THREAD

**Issue by tennisdad** [cptechie/homebridge-lutron-homeworks#4]
Hi,
I was wondering if you would be able to send specifics of the hardware Raspberry Pi module and Serial interface you have used to interface with the Lutron controller. 
I am trying to do the same but at a loss as to which raspberry pi solution to get - devices like Hoobs only have an Ethernet port so unsure how to interface with the Lutron system.
Thanks

**Comment by Ghostmif** [comment]
@tennisdad I suppose you can use USB-RS232 wire..I'm about to face the same problem - and this is the only sollution I've found
